parameters:
  - name: name
    type: string
  - name: nodeVersion
    type: string

jobs:
  - job: ${{ parameters.name }}
    displayName: Build/Test Node ${{ parameters.nodeVersion }}
    steps:
      - template: ./build.yaml
        parameters:
          nodeVersion: ${{ parameters.nodeVersion }}

      - script: npx @microsoft/rush test:ci
        displayName: Test
