parameters:
  - name: name
    type: string
  - name: nodeVersion
    type: string

jobs: 
  - job: ${{ parameters.name }}
    displayName: Build/Test Node ${{ parameters.nodeVersion }}
    steps:
      - task: NodeTool@0
          inputs:
            versionSpec: ${{ parameters.nodeVersion }}
          displayName: "Install Node.js  $(parameters.nodeVersion)"

      - script: |
          npm install -g npm 
          npx @microsoft/rush update
        displayName: "Rush install"

      - script: npx @microsoft/rush rebuild
        displayName: "Build"

      - script: npx @microsoft/rush test:ci
        displayName: Test
