parameters:
  - name: name
    type: string
  - name: nodeVersion
    type: string
  - name: vmImage
    type: string
    default: ubuntu-latest

jobs:
  - job: ${{ parameters.name }}
    displayName: Build/Test Node ${{ parameters.nodeVersion }} - ${{ parameters.vmImage }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ${{ parameters.nodeVersion }}
        displayName: Install Node.js  ${{ parameters.nodeVersion }}

      - script: npm install -g npm 
        displayName: Install dependencies

      - script: npx @microsoft/rush update
        displayName: Install dependencies

      - script: npx @microsoft/rush rebuild
        displayName: "Build"

      - script: npx @microsoft/rush test:ci
        displayName: Test
