parameters:
  - name: name
    type: string
  - name: nodeVersion
    type: string
  - name: vmImage
    type: string
    default: ubuntu-latest

jobs:
  - job: ${{ parameters.name }}
    displayName: Build/Test Node ${{ parameters.nodeVersion }} - ${{ parameters.vmImage }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
<<<<<<< HEAD
      - task: NodeTool@0
        inputs:
          versionSpec: ${{ parameters.nodeVersion }}
        displayName: Install Node.js  ${{ parameters.nodeVersion }}

      - script: npm install -g npm 
        displayName: Install dependencies

      - script: npx @microsoft/rush update
        displayName: Install dependencies

      - script: npx @microsoft/rush rebuild
        displayName: "Build"
=======
      - template: ./build.yaml
        parameters:
          nodeVersion: ${{ parameters.nodeVersion }}
>>>>>>> 469a5bfb533497800531e14714fd838ea2a17da5

      - script: npx @microsoft/rush test:ci
        displayName: Test
